# Generated by Django 3.1.6 on 2021-02-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='number',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='reminder',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
